curl brick.a.ssl.fastly.net/fonts/ebgaramond/400.woff -o ebgaramond-400.woff
curl brick.a.ssl.fastly.net/fonts/ebgaramond/400i.woff -o ebgaramond-400i.woff
curl brick.a.ssl.fastly.net/fonts/opensans/300.woff -o opensans-300.woff
curl brick.a.ssl.fastly.net/fonts/opensans/400.woff -o opensans-400.woff
curl brick.a.ssl.fastly.net/fonts/opensans/600.woff -o opensans-600.woff
curl brick.a.ssl.fastly.net/fonts/opensans/700.woff -o opensans-700.woff
curl brick.a.ssl.fastly.net/fonts/opensans/900.woff -o opensans-900.woff
curl brick.a.ssl.fastly.net/fonts/opensans/300i.woff -o opensans-300i.woff
curl brick.a.ssl.fastly.net/fonts/opensans/400i.woff -o opensans-400i.woff
curl brick.a.ssl.fastly.net/fonts/opensans/600i.woff -o opensans-600i.woff
curl brick.a.ssl.fastly.net/fonts/opensans/700i.woff -o opensans-700i.woff
curl brick.a.ssl.fastly.net/fonts/opensans/900i.woff -o opensans-900i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/100.woff -o raleway-100.woff
curl brick.a.ssl.fastly.net/fonts/raleway/200.woff -o raleway-200.woff
curl brick.a.ssl.fastly.net/fonts/raleway/300.woff -o raleway-300.woff
curl brick.a.ssl.fastly.net/fonts/raleway/400.woff -o raleway-400.woff
curl brick.a.ssl.fastly.net/fonts/raleway/500.woff -o raleway-500.woff
curl brick.a.ssl.fastly.net/fonts/raleway/600.woff -o raleway-600.woff
curl brick.a.ssl.fastly.net/fonts/raleway/700.woff -o raleway-700.woff
curl brick.a.ssl.fastly.net/fonts/raleway/800.woff -o raleway-800.woff
curl brick.a.ssl.fastly.net/fonts/raleway/900.woff -o raleway-900.woff
curl brick.a.ssl.fastly.net/fonts/raleway/100i.woff -o raleway-100i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/200i.woff -o raleway-200i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/300i.woff -o raleway-300i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/400i.woff -o raleway-400i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/500i.woff -o raleway-500i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/600i.woff -o raleway-600i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/700i.woff -o raleway-700i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/800i.woff -o raleway-800i.woff
curl brick.a.ssl.fastly.net/fonts/raleway/900i.woff -o raleway-900i.woff
